#------------------------------------------------------------
#|                                                          |
#|      _  _______        __     __    _____   ____         |
#|     | ||___ ___|      |  \   /  |  / ____| |  _ \        |
#|     | |   | |   ___   | |\\ //| | | (___   | | \ \       |
#|     | |   | |  / _ \  | | \_/ | |  \___ \  | |  ) )      |
#|     | |   | | | (_) | | |     | |  ____) | | |_/ /       |
#|     |_|   |_|  \___/  |_|     |_| |_____/  |____/        |
#|                                                          |
#|                                                          |
#------------------------------------------------------------
#|                 +==================+                     |
#|                 |    DeadlyWater   |                     |
#|                 |------------------|                     |
#|                 |        1.0       |                     |
#|                 |------------------|                     |
#|                 |  PolsatGraniePL  |                     |
#|                 +==================+                     |
#------------------------------------------------------------
#
# Hello, if you need help or have an idea that will improve our plugin,
#                   then be sure to contact us:
#
#  IToMSD Website: https://itomsd.com/
#  IToMSD Discord: https://dc.itomsd.com/
#  IToMSD SpigotMC: https://www.spigotmc.org/resources/authors/itomsd.1983449/




# List of worlds where water will deal damage

world_list:
  - worldd




# instant_death = Whether water should kill instantly or not
# damage_per_tick = Amount of damage dealt per tick

instant_death: false
damage_per_tick: 2




# Messages

plugin_reloaded: "&aDeadlyWater config reloaded."
no_permission: "&cYou do not have permission to perform this command."